services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Edge port for all AWS services
    environment:
      - SERVICES=s3,dynamodb,ec2    # Enable only required services
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1                        # Set to 1 for verbose logging
      - PERSISTENCE=/tmp/localstack_data  # Persist LocalStack state
    volumes:
      - "./localstack_data:/tmp/localstack_data"  # Volume for LocalStack data
      - "/var/run/docker.sock:/var/run/docker.sock"  # Mount Docker socket     
    networks:
      - localstack-network  
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    working_dir: /workspace
    depends_on:
      - localstack
    networks:
      - localstack-network    
    volumes:
      - ./terraform:/workspace
    entrypoint: ["tail", "-f", "/dev/null"] 
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb_admin
    depends_on:
      - localstack
    networks:
      - localstack-network  
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566     

volumes:
  localstack_data:
networks:
  localstack-network:
    driver: bridge      