version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"  # Exposes Redis on the default port
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  # Allows Redis to run without a password
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge